"""dded group model

Revision ID: 558f6bcf3cdf
Revises: fdb3c2d26033
Create Date: 2025-02-27 10:04:52.191070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558f6bcf3cdf'
down_revision: Union[str, None] = 'fdb3c2d26033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
