"""Added Group model

Revision ID: fdb3c2d26033
Revises: 04c9c973daa2
Create Date: 2025-02-23 11:49:19.032218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb3c2d26033'
down_revision: Union[str, None] = '04c9c973daa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'group_id')
    # ### end Alembic commands ###
